import 'disease_result.dart';
import 'sensor_data.dart';
class CropState { final String variety,growthStage,plantingDate; final int daysAfterPlanting; CropState.fromJson(Map<String,dynamic> j):variety=j['variety']??'',growthStage=j['growthStage']??'',plantingDate=j['plantingDate']??'',daysAfterPlanting=(j['daysAfterPlanting']??0).toInt(); }
class RiskState { final double environmentalRisk,diseaseRisk,combinedRisk; final String riskLevel; RiskState.fromJson(Map<String,dynamic> j):environmentalRisk=(j['environmentalRisk']??0).toDouble(),diseaseRisk=(j['diseaseRisk']??0).toDouble(),combinedRisk=(j['combinedRisk']??0).toDouble(),riskLevel=j['riskLevel']??'Low'; }
class PredictionState { final double current,after1Hour,after3Hours,after6Hours; final bool irrigationRequired; final String model; PredictionState.fromJson(Map<String,dynamic> j):current=(j['current']??0).toDouble(),after1Hour=(j['after1Hour']??0).toDouble(),after3Hours=(j['after3Hours']??0).toDouble(),after6Hours=(j['after6Hours']??0).toDouble(),irrigationRequired=j['irrigationRequired']==true,model=j['model']??''; }
class Recommendation { final String priority,category,title,message; final List<String> reasons; Recommendation.fromJson(Map<String,dynamic> j):priority=j['priority']??'',category=j['category']??'',title=j['title']??'',message=j['message']??'',reasons=List<String>.from(j['reasons']??[]); }
class ActuatorState { final String pump; ActuatorState.fromJson(Map<String,dynamic> j):pump=j['pump']??'OFF'; }
class DigitalTwinData {
 final bool online; final String zoneId,synchronizationStatus; final SensorData? sensorData; final DiseaseResult? latestDiagnosis; final String? latestImage; final DateTime? lastSensorUpdate,lastCameraCapture; final CropState? cropState; final RiskState? riskState; final PredictionState? predictionState; final Recommendation? recommendation; final ActuatorState? actuatorState;
 DigitalTwinData({required this.online,required this.zoneId,required this.synchronizationStatus,this.sensorData,this.latestDiagnosis,this.latestImage,this.lastSensorUpdate,this.lastCameraCapture,this.cropState,this.riskState,this.predictionState,this.recommendation,this.actuatorState});
 factory DigitalTwinData.fromJson(Map<String,dynamic> j)=>DigitalTwinData(online:j['online']==true,zoneId:j['zoneId']??'zone_1',synchronizationStatus:j['synchronizationStatus']??'OFFLINE',sensorData:j['sensorData'] is Map?SensorData.fromJson(Map<String,dynamic>.from(j['sensorData'])):null,latestDiagnosis:j['latestDiagnosis'] is Map?DiseaseResult.fromJson(Map<String,dynamic>.from(j['latestDiagnosis'])):null,latestImage:j['latestImage']?.toString(),lastSensorUpdate:DateTime.tryParse(j['lastSensorUpdate']?.toString()??''),lastCameraCapture:DateTime.tryParse(j['lastCameraCapture']?.toString()??''),cropState:j['cropState'] is Map?CropState.fromJson(Map<String,dynamic>.from(j['cropState'])):null,riskState:j['riskState'] is Map?RiskState.fromJson(Map<String,dynamic>.from(j['riskState'])):null,predictionState:j['predictionState'] is Map?PredictionState.fromJson(Map<String,dynamic>.from(j['predictionState'])):null,recommendation:j['recommendation'] is Map?Recommendation.fromJson(Map<String,dynamic>.from(j['recommendation'])):null,actuatorState:j['actuatorState'] is Map?ActuatorState.fromJson(Map<String,dynamic>.from(j['actuatorState'])):null);
}
